{{- if include "jiramcp.hasConfigFiles" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jiramcp.fullname" . }}
  labels:
    {{- include "jiramcp.labels" . | nindent 4 }}
data:
  {{- if include "jiramcp.hasMapping" . }}
  team-mapping.yaml: |
{{ .Values.teamMapping.inlineYaml | indent 4 }}
  {{- end }}
  {{- if include "jiramcp.oidc" . }}
  group-projects.yaml: |
{{ .Values.oidc.groupProjects | indent 4 }}
  {{- end }}
{{- end }}
